export const GET_TOKEN_DETAILS_REQUESTED = 'GET_TOKEN_DETAILS_REQUESTED'
export const GET_TOKEN_DETAILS_SUCCEEDED = 'GET_TOKEN_DETAILS_SUCCEEDED'
export const GET_TOKEN_DETAILS_ERROR = 'GET_TOKEN_DETAILS_ERROR'