export const GET_INTENT_DETAILS_REQUESTED = 'GET_INTENT_DETAILS_REQUESTED'
export const GET_INTENT_DETAILS_SUCCEEDED = 'GET_INTENT_DETAILS_SUCCEEDED'
export const GET_INTENT_DETAILS_ERROR = 'GET_INTENT_DETAILS_ERROR'
